### ISSUE TITLE
Exception on Non-whitelisted IP

### ISSUE THREAD

**Issue by brannondorsey** [brannondorsey/pastebin-mirror#1]
Run program from whitelisted IP behind VPN. Turn off VPN. Exception.

**Comment by brannondorsey** [comment]
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "pastebin-mirror/__main__.py", line 107, in <module>
    main()
  File "pastebin-mirror/__main__.py", line 102, in main
    last_scrape = archive_scrape_pastes(last_scrape, scraper, storage, args.rate)
  File "pastebin-mirror/__main__.py", line 48, in archive_scrape_pastes
    recent_pastes = [x for x in scraper.get_recent_pastes() \
  File "pastebin-mirror/scraper.py", line 66, in get_recent_pastes
    return paste_list.json()
  File "/media/raid/brannon/pastebin-mirror/venv/lib/python3.4/site-packages/requests/models.py", line 886, in json
    self.content.decode(encoding), **kwargs
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

```
