### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by brannondorsey** [brannondorsey/pastebin-mirror#3]
```
[*] Waiting 30 seconds before next paste scrape
[!] Exception making request to https://pastebin.com/api_scraping.php
[*] Fetching 0 new pastes
[*] Waiting 30 seconds before next paste scrape
[!] Exception making request to https://pastebin.com/api_scraping.php
[*] Fetching 0 new pastes
[*] Waiting 30 seconds before next paste scrape
[!] Exception making request to https://pastebin.com/api_scraping.php
[*] Fetching 0 new pastes
[*] Waiting 30 seconds before next paste scrape
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "pastebin-mirror/__main__.py", line 107, in <module>
    main()
  File "pastebin-mirror/__main__.py", line 102, in main
    last_scrape = archive_scrape_pastes(last_scrape, scraper, storage, args.rate)
  File "pastebin-mirror/__main__.py", line 48, in archive_scrape_pastes
    recent_pastes = [x for x in scraper.get_recent_pastes() \
  File "pastebin-mirror/scraper.py", line 66, in get_recent_pastes
    return paste_list.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 800, in json
    self.content.decode(encoding), **kwargs
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by brannondorsey** [comment]
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "pastebin-mirror/__main__.py", line 166, in <module>
    main()
  File "pastebin-mirror/__main__.py", line 153, in main
    last_scrape = archive_scrape_pastes(last_scrape, scraper, storage, args.rate, args.quiet)
  File "pastebin-mirror/__main__.py", line 57, in archive_scrape_pastes
    recent_pastes = [x for x in scraper.get_recent_pastes() \
  File "pastebin-mirror/scraper.py", line 52, in get_recent_pastes
    return paste_list.json()
  File "/media/raid/brannon/pastebin-mirror/venv/lib/python3.4/site-packages/requests/models.py", line 894, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```

**Comment by brannondorsey** [comment]
```
[*] Total pastes downloaded this session: 163111
[*] Waiting 30 seconds before next paste scrape
[*] Fetching 14 new pastes.
[!] Request to https://pastebin.com/raw/bNVxvj3e returned non-200 code
[!] Request to https://pastebin.com/raw/nQPs9R5N returned non-200 code
[!] Request to https://pastebin.com/raw/VA75Vgxs returned non-200 code
[!] Request to https://pastebin.com/raw/Mhy4S67X returned non-200 code
[!] Request to https://pastebin.com/raw/njhfVCSw returned non-200 code
[!] Request to https://pastebin.com/raw/7FuLkYRj returned non-200 code
[!] Request to https://pastebin.com/raw/FBbiD9em returned non-200 code
[!] Request to https://pastebin.com/raw/5c4FsYLm returned non-200 code
[!] Request to https://pastebin.com/raw/Sg5eWSEY returned non-200 code
[!] Request to https://pastebin.com/raw/TyBHaWFY returned non-200 code
[!] Request to https://pastebin.com/raw/qw7NeFvm returned non-200 code
[!] Request to https://pastebin.com/raw/Ju5Zyr71 returned non-200 code
[!] Request to https://pastebin.com/raw/JM9G4bWQ returned non-200 code
[!] Request to https://pastebin.com/raw/u9eqVHA2 returned non-200 code
[*] Total pastes downloaded this session: 163125
[*] Waiting 30 seconds before next paste scrape
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "pastebin-mirror/__main__.py", line 168, in <module>
    main()
  File "pastebin-mirror/__main__.py", line 155, in main
    last_scrape = archive_scrape_pastes(last_scrape, scraper, storage, args.rate, args.quiet)
  File "pastebin-mirror/__main__.py", line 57, in archive_scrape_pastes
    recent_pastes = [x for x in scraper.get_recent_pastes() \
  File "pastebin-mirror/scraper.py", line 52, in get_recent_pastes
    return paste_list.json()
  File "/media/raid/brannon/pastebin-mirror/venv/lib/python3.4/site-packages/requests/models.py", line 886, in json
    self.content.decode(encoding), **kwargs
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```
